version: '3.3'
services:
  demo-microservice:
    env_file:
      .env
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: demo-microservice
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - db_volume:/data/db

volumes:
  db_volume: